export const INPUT_VALUE = 'INPUT_VALUE';
export const SELECT_VALUE = 'SELECT_VALUE';
export const FETCHING_BOOKS = 'FETCHING_BOOKS';
export const CHOSEN_BOOK = 'CHOSEN_BOOK';
export const IS_AUTHORISED = 'IS_AUTHORISED';
export const RECOMENDATIONS = 'RECOMENDATIONS';
